### ISSUE TITLE
Rachel of the Rust Clan

### ISSUE THREAD

**Issue by rachknudson** [EdHubbell/RustClock#1]
Wow I am an idiot!  I plugged the clock back in and can't figure out how to get it to work again.  I found this script, but don't remember what to do with it.  I saved the paper with all the numbers on it.  Found that!  Now it is taped to the back of the clock.  Ed Rocks the world!

**Comment by EdHubbell** [comment]
I'm not clear on whether this means you got it working or not. But I'm going to take the 'Ed rocks the world' comment as a positive, and mark this issue as resolved.

**Comment by EdHubbell** [comment]
No comment.

**Comment by rachknudson** [comment]
I did not!  You still rock though!

Rachel Knudson

**Comment by rachknudson** [comment]
So question:. You did not replace any of the light bulbs?  Many are out and
I was looking to pass this to my sister

How are you hun??

Rachel Knudson

**Comment by EdHubbell** [comment]
I did replace bulbs. Not sure where I got them from. Looks like you could
try these Amazon bulbs -

https://www.amazon.com/Bayonet-Nonpolarity-Pinball-Bulbs-Machine/dp/B094QSS1FG/ref=pd_day0fbt_img_sccl_2/143-0137674-6397212?pd_rd_w=lHXoM&content-id=amzn1.sym.0a3d352f-2699-4ba2-810c-59dcb4abfa1b&pf_rd_p=0a3d352f-2699-4ba2-810c-59dcb4abfa1b&pf_rd_r=C9ZXV7J9QE3ZYTCDH2MR&pd_rd_wg=ArdXo&pd_rd_r=1e5b1d2e-7935-486c-8171-5cd4d243e71b&pd_rd_i=B094QSS1FG&th=1

Then it would be LED. I'd buy one set before buying all 3 colors, tho -
Just to make sure they work.

I'm sick of this hospital, and I'm thirsty. Hopefully I'll be helped up to
go for a walk in a little while. Can't leave without permissions, Hope
y'all are doing well! Yes, that clock should stay in the family definitely.

~Ed
